-- Loop Cognitive Architecture — Increment 3
-- (explainability + publisher + per-subscriber delivery + decision policies)
--
-- ADDITIVE ONLY. One new enum, one new table, two ADD COLUMN, four indexes.
-- Zero DROP, zero rename, zero column-type change. Every existing row keeps its
-- meaning: `required` defaults false (optional), `idempotencyKey` defaults NULL
-- (NULLs are distinct in Postgres, so the new unique binds only keyed rows).
--
-- Generated by `prisma migrate diff` (datamodel→datamodel); see
-- docs/architecture/migration-remediation-plan.md for how it participates in the
-- future baseline.

-- CreateEnum
CREATE TYPE "DeliveryStatus" AS ENUM ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'DEAD_LETTERED');

-- AlterTable
ALTER TABLE "state_change_subscriptions" ADD COLUMN     "required" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "cognitive_decisions" ADD COLUMN     "idempotencyKey" TEXT;

-- CreateTable
CREATE TABLE "state_change_deliveries" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "outboxId" TEXT NOT NULL,
    "subscriptionId" TEXT NOT NULL,
    "subscriberKey" TEXT NOT NULL,
    "idempotencyKey" TEXT NOT NULL,
    "required" BOOLEAN NOT NULL DEFAULT false,
    "status" "DeliveryStatus" NOT NULL DEFAULT 'PENDING',
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "availableAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "lastError" TEXT,
    "resultSummary" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "state_change_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "state_change_deliveries_organizationId_status_availableAt_idx" ON "state_change_deliveries"("organizationId", "status", "availableAt");

-- CreateIndex
CREATE INDEX "state_change_deliveries_organizationId_outboxId_idx" ON "state_change_deliveries"("organizationId", "outboxId");

-- CreateIndex
CREATE UNIQUE INDEX "state_change_deliveries_outboxId_subscriptionId_key" ON "state_change_deliveries"("outboxId", "subscriptionId");

-- CreateIndex
CREATE UNIQUE INDEX "cognitive_decisions_organizationId_idempotencyKey_key" ON "cognitive_decisions"("organizationId", "idempotencyKey");
