import { SidebarIcon } from '../../crm/_brand/SidebarIcon';

/*
 * Admin dashboard — Loop OS control center (PR #48).
 * PRESENTATION ONLY. Every figure below is a static placeholder; no data is
 * wired, no Brain call is made, no query is run.
 */

type Metric = {
  label: string;
  value: string;
  delta?: string;
  tone?: 'up' | 'down';
  icon: string;
  chip?: { text: string; kind: string };
};

const METRICS: Metric[] = [
  { label: 'Business Health', value: '94%', delta: '+2.1% this week', tone: 'up', icon: 'building', chip: { text: 'Healthy', kind: 'good' } },
  { label: 'Marketplace Health', value: 'Stable', delta: 'All sensors reporting', tone: 'up', icon: 'chart', chip: { text: 'Nominal', kind: 'good' } },
  { label: 'Revenue', value: '—', delta: 'Awaiting data', icon: 'revenue', chip: { text: 'Placeholder', kind: 'info' } },
  { label: 'Profit', value: '—', delta: 'Awaiting data', icon: 'revenue', chip: { text: 'Placeholder', kind: 'info' } },
];

const ALERTS: Metric[] = [
  { label: 'Critical Alerts', value: '0', delta: 'Nothing needs attention', tone: 'up', icon: 'bell', chip: { text: 'Clear', kind: 'good' } },
  { label: 'Brain Status', value: 'Online', delta: 'Reasoning layer active', tone: 'up', icon: 'brain', chip: { text: 'Online', kind: 'good' } },
  { label: 'Creator Queue', value: '—', delta: 'No submissions yet', icon: 'star', chip: { text: 'Empty', kind: 'info' } },
  { label: 'Businesses Waiting', value: '—', delta: 'None pending', icon: 'building', chip: { text: 'Empty', kind: 'info' } },
];

export default function ADMINDashboard() {
  return (
    <>
      <div className="loop-pagehead">
        <div className="loop-eyebrow">Loop OS · Control Center</div>
        <h1 className="loop-title">What deserves your attention</h1>
        <p className="loop-subtitle">
          A single view across the operating system. Figures shown are
          placeholders — live signals from the Brain and Marketplace
          Intelligence plug in here in a later phase.
        </p>
      </div>
      <div className="loop-grid cols-4" style={{ marginBottom: 16 }}>
        {METRICS.map((m) => (
          <div className="loop-card" key={m.label}>
            <div className="loop-card__head">
              <span className="loop-card__label"><SidebarIcon name={m.icon} /> {m.label}</span>
              {m.chip ? <span className={'loop-chip ' + m.chip.kind}>{m.chip.text}</span> : null}
            </div>
            <div className="loop-card__metric">{m.value}</div>
            {m.delta ? <div className={'loop-card__delta ' + (m.tone ?? '')}>{m.delta}</div> : null}
          </div>
        ))}
      </div>
      <div className="loop-grid cols-4" style={{ marginBottom: 24 }}>
        {ALERTS.map((m) => (
          <div className="loop-card" key={m.label}>
            <div className="loop-card__head">
              <span className="loop-card__label"><SidebarIcon name={m.icon} /> {m.label}</span>
              {m.chip ? <span className={'loop-chip ' + m.chip.kind}>{m.chip.text}</span> : null}
            </div>
            <div className="loop-card__metric">{m.value}</div>
            {m.delta ? <div className={'loop-card__delta ' + (m.tone ?? '')}>{m.delta}</div> : null}
          </div>
        ))}
      </div>
      <div className="loop-grid cols-3">
        <div className="loop-card">
          <div className="loop-card__head">
            <span className="loop-card__label"><SidebarIcon name="brain" /> Brain Briefing</span>
            <span className="loop-chip info">Preview</span>
          </div>
          <div className="loop-row"><span className="grow">Daily briefing will appear here</span></div>
          <div className="loop-row"><span className="grow muted">Generated by the Brain · read-only</span></div>
          <div className="loop-skel" style={{ height: 12, marginTop: 12 }} />
          <div className="loop-skel" style={{ height: 12, marginTop: 8, width: '80%' }} />
        </div>
        <div className="loop-card">
          <div className="loop-card__head">
            <span className="loop-card__label"><SidebarIcon name="activity" /> Recent Activity</span>
          </div>
          <div className="loop-row"><span className="grow">Marketplace sensor connected</span><span className="muted">now</span></div>
          <div className="loop-row"><span className="grow">Brain reasoning layer online</span><span className="muted">now</span></div>
          <div className="loop-row"><span className="grow">Workspace shells initialized</span><span className="muted">now</span></div>
        </div>
        <div className="loop-card">
          <div className="loop-card__head">
            <span className="loop-card__label"><SidebarIcon name="flow" /> Quick Actions</span>
          </div>
          <div className="loop-row"><span className="grow">Review Marketplace</span><span className="val">→</span></div>
          <div className="loop-row"><span className="grow">Open the Brain</span><span className="val">→</span></div>
          <div className="loop-row"><span className="grow">Experiments</span><span className="muted">Soon</span></div>
        </div>
      </div>
    </>
  );
}
