-- PR #75 — Work OS Blueprint Runtime v1
-- ---------------------------------------------------------------------------
-- HAND-WRITTEN migration. This was NOT generated by `prisma migrate dev`.
-- It is authored to match the models appended to schema.prisma in this PR.
-- Before this is applied in an environment with database access, the team
-- should run `prisma migrate diff` / `prisma migrate dev` to regenerate /
-- validate against the live schema. Column names, table names (@@map) and
-- indexes here are kept in sync with the Prisma models by hand.
--
-- v1 tradeoff: organizationId / userId columns are plain scalars with NO
-- foreign keys to organizations/users, to keep this migration purely
-- additive (no changes to existing core tables).
-- ---------------------------------------------------------------------------

-- CreateTable
CREATE TABLE "blueprints" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdByUserId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "blueprints_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "blueprint_stages" (
    "id" TEXT NOT NULL,
    "blueprintId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "position" INTEGER NOT NULL,
    "defaultOwnerUserId" TEXT,
    "requiresApproval" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "blueprint_stages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "work_instances" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "blueprintId" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "currentStageId" TEXT,
    "createdByUserId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "completedAt" TIMESTAMP(3),
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "work_instances_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "work_stages" (
    "id" TEXT NOT NULL,
    "workInstanceId" TEXT NOT NULL,
    "blueprintStageId" TEXT,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "position" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "ownerUserId" TEXT,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "completedByUserId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "work_stages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "work_assignments" (
    "id" TEXT NOT NULL,
    "workInstanceId" TEXT NOT NULL,
    "workStageId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "assignedByUserId" TEXT,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "unassignedAt" TIMESTAMP(3),
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "work_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "work_notifications" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "workInstanceId" TEXT NOT NULL,
    "workStageId" TEXT,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "work_notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "work_comments" (
    "id" TEXT NOT NULL,
    "workInstanceId" TEXT NOT NULL,
    "workStageId" TEXT,
    "userId" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "work_comments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "blueprints_organizationId_status_idx" ON "blueprints"("organizationId", "status");

-- CreateIndex
CREATE INDEX "blueprint_stages_blueprintId_position_idx" ON "blueprint_stages"("blueprintId", "position");

-- CreateIndex
CREATE INDEX "work_instances_organizationId_status_idx" ON "work_instances"("organizationId", "status");

-- CreateIndex
CREATE INDEX "work_stages_ownerUserId_status_idx" ON "work_stages"("ownerUserId", "status");

-- CreateIndex
CREATE INDEX "work_stages_workInstanceId_position_idx" ON "work_stages"("workInstanceId", "position");

-- CreateIndex
CREATE INDEX "work_assignments_userId_idx" ON "work_assignments"("userId");

-- CreateIndex
CREATE INDEX "work_assignments_workStageId_idx" ON "work_assignments"("workStageId");

-- CreateIndex
CREATE INDEX "work_notifications_userId_readAt_idx" ON "work_notifications"("userId", "readAt");

-- CreateIndex
CREATE INDEX "work_comments_workInstanceId_idx" ON "work_comments"("workInstanceId");

-- AddForeignKey
ALTER TABLE "blueprint_stages" ADD CONSTRAINT "blueprint_stages_blueprintId_fkey" FOREIGN KEY ("blueprintId") REFERENCES "blueprints"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "work_stages" ADD CONSTRAINT "work_stages_workInstanceId_fkey" FOREIGN KEY ("workInstanceId") REFERENCES "work_instances"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "work_notifications" ADD CONSTRAINT "work_notifications_workInstanceId_fkey" FOREIGN KEY ("workInstanceId") REFERENCES "work_instances"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "work_comments" ADD CONSTRAINT "work_comments_workInstanceId_fkey" FOREIGN KEY ("workInstanceId") REFERENCES "work_instances"("id") ON DELETE CASCADE ON UPDATE CASCADE;
