-- Commercial Intelligence Stage 3 correctness: provider member expectation.
--
-- ADDITIVE ONLY. One new table, one lookup index, two foreign keys, one CHECK
-- constraint and one EXCLUDE constraint. Zero DROP. Zero rename. Zero column-type
-- change. No existing row is read, rewritten or backfilled, and NO EXPECTATION
-- ROW IS SEEDED: what a campaign's state was on a past date is a human statement,
-- and inventing one here would manufacture the history this table exists to
-- record honestly.
--
-- ASCII ONLY. A leading em-dash in the sprint_11 migration blocked replay of the
-- entire ledger once (see PR #152); this header is deliberately plain ASCII.
--
-- provider_member_expectations
--   Whether records from one provider population member were SUPPOSED to reach
--   Loop on a given business date. provider_observation_days proves Loop looked;
--   reconciliation proves what arrived; neither can say whether an absence was a
--   defect. On 2026-08-05 CallGrid held 974 call identities and Loop held 867,
--   and 9 of those 107 absences belonged to campaigns whose webhook was never
--   attached -- correct absences, indistinguishable from failures without a human
--   statement. This table is that statement.
--
--   EFFECTIVE-DATED, half-open: "effectiveFrom" is INCLUSIVE, "effectiveTo" is
--   EXCLUSIVE, NULL means still in force. A campaign connected on 2026-08-19 gets
--   a new declaration from that date; the row covering 2026-08-05 keeps saying
--   what was true then. A current-state flag would retroactively convert every
--   prior day into a delivery failure nobody could have prevented.
--
--   UNKNOWN IS NOT STORABLE. Only EXPECTED, NOT_CONFIGURED and EXCLUDED are
--   declarable. "Nobody has said" is the ABSENCE of a row covering the date --
--   the same convention as the absence of an observation row certifying nothing
--   -- and it fails closed at the measurement gate.
--
--   state, memberDimension, basis and exclusionReason are TEXT rather than
--   enums, following objective_measure_bindings.metric: the vocabularies live in
--   @emgloop/shared and are validated on the way in and on the way out, so
--   widening one is a contract change rather than production DDL against a table
--   whose migrations are human-dispatched.
--
-- Tenancy: a real foreign key with defined delete behaviour, and organizationId
-- leads the lookup index and both constraints. integration_events is uniquely
-- keyed (provider, externalId) GLOBALLY and cannot be repaired in callers; this
-- table deliberately does not repeat that, so one organization's declaration can
-- never resolve another organization's member.

-- CreateTable
CREATE TABLE "provider_member_expectations" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "stream" TEXT NOT NULL,
    "memberDimension" TEXT NOT NULL,
    "memberExternalId" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "exclusionReason" TEXT,
    "basis" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "effectiveFrom" DATE NOT NULL,
    "effectiveTo" DATE,
    "declaredByUserId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "provider_member_expectations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "provider_member_expectations_member_effective_idx" ON "provider_member_expectations"("organizationId", "provider", "stream", "memberDimension", "memberExternalId", "effectiveFrom");

-- AddForeignKey
ALTER TABLE "provider_member_expectations" ADD CONSTRAINT "provider_member_expectations_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_member_expectations" ADD CONSTRAINT "provider_member_expectations_declaredByUserId_fkey" FOREIGN KEY ("declaredByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- HAND-WRITTEN SQL BELOW. Prisma cannot express either constraint, and both
-- enforce an invariant this table would otherwise be trusting callers to keep.
-- Everything above this line was generated by `prisma migrate diff`.
-- ---------------------------------------------------------------------------

-- A declaration that ends before it starts is a defect, and a declaration that
-- ends ON its start date says nothing about any date at all. Postgres would
-- accept both as ordinary rows; the range operators below would not catch the
-- second, because an EMPTY range overlaps nothing and would slip past the
-- exclusion constraint as a phantom declaration nobody could resolve.
ALTER TABLE "provider_member_expectations"
    ADD CONSTRAINT "provider_member_expectations_effective_range_check"
    CHECK ("effectiveTo" IS NULL OR "effectiveTo" > "effectiveFrom");

-- AT MOST ONE DECLARATION IN FORCE PER MEMBER PER DATE, enforced by the database.
--
-- Two rows covering one business date mean the organization has said two things
-- about the same campaign, and no tie-break exists that would not be invented
-- here. The pure resolver in @emgloop/shared already fails closed to UNKNOWN when
-- it sees more than one match, and the repository refuses to write an overlap --
-- but application-level uniqueness is exactly the guarantee Sprint 29A proved
-- cannot be sustained by review, and two concurrent declarations would each pass
-- their own pre-check and both commit.
--
-- btree_gist supplies the "=" operator class GiST needs for the scalar key
-- columns; without it an exclusion constraint cannot mix equality on TEXT with
-- range overlap. The extension is available on Neon and the statement is
-- idempotent. IF THE DEPLOY ROLE LACKS CREATE privileges on the database this
-- statement fails and the migration stops -- deliberately, because the table is
-- worth less without the constraint than the deploy is worth without the table.
--
-- The range is half-open '[)' so back-to-back declarations do NOT collide:
-- [Aug 1, Aug 19) and [Aug 19, NULL) touch at Aug 19 and overlap on no date,
-- which is exactly what closing one declaration and opening the next produces.
-- A NULL "effectiveTo" is an unbounded upper bound, so two open-ended
-- declarations for one member always collide.
CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE "provider_member_expectations"
    ADD CONSTRAINT "provider_member_expectations_no_overlap"
    EXCLUDE USING gist (
        "organizationId" WITH =,
        "provider" WITH =,
        "stream" WITH =,
        "memberDimension" WITH =,
        "memberExternalId" WITH =,
        daterange("effectiveFrom", "effectiveTo", '[)') WITH &&
    );
